# Generated by Django 4.2.5 on 2023-10-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_coursess_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursess',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
